### ISSUE TITLE
error: "utf8.decode is not a function"

### ISSUE THREAD

**Issue by MillerGregor** [leethree/redux-persist-fs-storage#3]
For anyone else getting this error:

There's a naming collision between the "utf8" package and react-native's internal utf8 library.

@eacbkk forked utf8 to rename it:
https://github.com/eacbkk/utf8.js

I've forked redux-persist-fs-storage and forked @tianling536's fork of react-native-fs to avoid the utf8 error and get RN 0.5x.x support:

https://github.com/Gregor1971/redux-persist-fs-storage
https://github.com/Gregor1971/react-native-fs

**Comment by leethree** [comment]
Thanks for your report! This looks like an issue of `react-native-fs`. Could you file an issue there?

**Comment by MillerGregor** [comment]
Yes, I meant to do that.  Here's a link:  itinance/react-native-fs#422

Obviously, you can close this.  I just wanted something to turn up when people search.

The RN team knows about this:  facebook/react-native/pull/17146

**Comment by leethree** [comment]
This is fixed in upstream: https://github.com/facebook/react-native/pull/17146
