### ISSUE TITLE
Cannot read 'RNFSFileTypeRegular' of undefined 

### ISSUE THREAD

**Issue by AliaMYH** [leethree/redux-persist-fs-storage#4]
I'm using FSStorage as my redux-persist engine, in the following way : 

```
import { createStore, applyMiddleware } from 'redux';
import thunk from 'redux-thunk';
import rootReducer from '../reducers';
import { persistStore, persistReducer, autoRehydrate } from 'redux-persist'
import FSStorage from 'redux-persist-fs-storage';

import Reactotron from 'reactotron-react-native';

const persistConfig = {
 key: 'root',
 storage: FSStorage,
 whitelist: ['user', 'login', 'getKey', 'cart', 'orderDetails'] // see "Merge Process" section for details.
};

const persistRed = persistReducer(persistConfig, rootReducer);

export const store = createStore(
  persistRed,
  initialState,
  applyMiddleware(thunk),
  autoRehydrate(),
  window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
);

export const persistor = persistStore(store);

```
Then I simply import the store and persister and use them in my component:

```
<Provider store={store}>
          <PersistGate loading={<Text>Loading</Text>} persistor={persistor}>
            <PrimaryNav />
          </PersistGate>
</Provider>
```

But I get the following error : 

```
Cannot read property 'RNFSFileTypeRegular' of undefined
<unknown>
    FS.common.js:18:38
loadModuleImplementation
    require.js:213:4
guardedLoadModule
    require.js:147:11
_require
    require.js:131:2
<unknown>
    index.js:2
loadModuleImplementation
    require.js:213:4
guardedLoadModule
    require.js:147:11
_require
    require.js:131:2
<unknown>
    configureStore.js:5
loadModuleImplementation
    require.js:213:4
```

Not sure what's causing the error.

**Comment by leethree** [comment]
@AliaMYH Looks like `react-native-fs` native code is not linked corrected. Did you run this command?
```
react-native link react-native-fs
```

**Comment by vishnukalakota** [comment]
`react-native link react-native-fs` this didn't fix it 

same issue here

**Comment by leethree** [comment]
It seems like the error is caused by `react-native-fs` not supporting `expo` (or CRNA projects). You can find a lot of reports of the same error if you [search in `react-native-fs` issues](https://github.com/itinance/react-native-fs/issues?q=RNFSFileTypeRegular).

If you are using `expo` or CRNA, you might need to detach ExpoKit (see https://github.com/itinance/react-native-fs/issues/349#issuecomment-331913057). 

Otherwise you might need to link manually: https://facebook.github.io/react-native/docs/linking-libraries-ios.html

**Comment by leethree** [comment]
Also you might want to take a look at [redux-persist-expo-fs-storage](https://github.com/techwes/redux-persist-expo-fs-storage) if you are using ExpoKit.
