### ISSUE TITLE
Upgrade react-native-fs

### ISSUE THREAD

**Issue by Amnesthesia** [leethree/redux-persist-fs-storage#8]
For recent versions of React Native (e.g 0.57), react-native-fs 2.12 is required, but this package depends on 2.10

**Comment by leethree** [comment]
Would appreciate it if you could create a PR to upgrade the dependency. Thanks!

**Comment by MakhouT** [comment]
@leethree Any news on this?

**Comment by leethree** [comment]
Actually because `react-native-fs` 2.12 is an in-range update, you should be able to upgrade `react-native-fs` without problem.

**Comment by leethree** [comment]
Dependencies are updated in `v1.3.0`. Let me know if you found other issues. Thanks!
